name: Auto Promote & Update

on:
  schedule:
    - cron: '49 * * * *'
  workflow_dispatch:

jobs:
  promote:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: pip install selenium
      
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest
      
      - name: Run bot
        env:
          TUNWALAI_USERNAME: ${{ secrets.TUNWALAI_USERNAME }}
          TUNWALAI_PASSWORD: ${{ secrets.TUNWALAI_PASSWORD }}
          STORY_IDS: ${{ vars.STORY_IDS }}
        run: python bot.py

